# Generated by Django 3.2.5 on 2022-02-07 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Book',
        ),
    ]
