# Generated by Django 3.2.5 on 2022-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_pictures_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
